# Generated by Django 3.0 on 2021-12-30 08:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleMeeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_meeting_date_time', models.DateTimeField()),
                ('to_meeting_date_time', models.DateTimeField()),
                ('meeting_time_interval', models.CharField(choices=[('15 MIN', '15 MIN'), ('30 MIN', '30 MIN'), ('45 MIN', '45 MIN')], max_length=30)),
                ('is_booked', models.BooleanField(default=False)),
                ('user_name', models.CharField(blank=True, max_length=255, null=True)),
                ('user_email', models.CharField(blank=True, max_length=255, null=True)),
                ('meeting_creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
